platform :ios, '16.0'

target 'PokeDexBasic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'Alamofire'
  pod 'RealmSwift'

  # Pods for PokeDexBasic

  target 'PokeDexBasicTests' do
    inherit! :search_paths
  end

  target 'PokeDexBasicUITests' do
    # Pods for testing
  end

end
