platform :ios, '13.0'

target 'PokeDexBasic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeDexBasic

  target 'PokeDexBasicTests' do
    inherit! :search_paths
    pod 'Alamofire'
    pod 'RealmSwift'
  end

  target 'PokeDexBasicUITests' do
    # Pods for testing
  end

end
